# Common configuration.
AllCops:
  # Include common Ruby source files.
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'backup/**/*'
    - 'bundler_stubs/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - '.bundle/**/*'
    - 'config/initializers/**'
    - 'config/environments/**'
    - 'config/application.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'spec/support/**/*'
    - 'app/controllers/concerns/broadcasted.rb'
    - 'Gemfile.lock'
    - 'Gemfile'
    - 'features/step_definitions/email_steps.rb'

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
#Style/ClassAndModuleChildren:
#  # Checks the style of children definitions at classes and modules.
#  #
#  # Basically there are two different styles:
#  #
#  # `nested` - have each child on a separate line
#  #   class Foo
#  #     class Bar
#  #     end
#  #   end
#  #
#  # `compact` - combine definitions as much as possible
#  #   class Foo::Bar
#  #   end
#  #
#  # The compact style is only forced, for classes / modules with one child.
#  EnforcedStyle: compact
#  SupportedStyles:
#    - nested
#    - compact

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
