# Common configuration.
AllCops:
  # Include common Ruby source files.

  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'backup/**/*'
    - 'bundler_stubs/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - '.bundle/**/*'
    - 'config/initializers/**'
    - 'config/environments/**'
    - 'config/application.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'spec/support/**/*'

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false