# Common configuration.
AllCops:
  # Include common Ruby source files.

  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'backup/**/*'
    - 'bundler_stubs/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - '.bundle/**/*'
    - 'config/initializers/**'
    - 'config/environments/**'
    - 'config/application.rb'

Metrics/LineLength:
  Max: 120